// generated by bindgen
extern "C" {
    pub fn luauL_newstate() -> *mut ::std::os::raw::c_void;
    pub fn luauL_openlibs(L: *mut ::std::os::raw::c_void);
    pub fn luauL_dostring(L: *mut ::std::os::raw::c_void, s: *const i8) -> i32;
    pub fn luau_tolstring(L: *mut ::std::os::raw::c_void, idx: i32, len: *mut usize) -> *const i8;
    pub fn luau_close(L: *mut ::std::os::raw::c_void);
}
